"""rename uci to san

Revision ID: 1aa995770ec9
Revises: 5a8d0df06663
Create Date: 2025-08-23 13:58:19.733314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1aa995770ec9'
down_revision: Union[str, Sequence[str], None] = '5a8d0df06663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferred_move', sa.Column('san', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('preferred_move', 'uci')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferred_move', sa.Column('uci', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('preferred_move', 'san')
    # ### end Alembic commands ###
