"""initial tables

Revision ID: 5a8d0df06663
Revises: 
Create Date: 2025-08-21 13:36:46.941942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5a8d0df06663'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('white_player_id', sa.Uuid(), nullable=True),
    sa.Column('black_player_id', sa.Uuid(), nullable=True),
    sa.Column('winner', sa.Boolean(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_black_player_id'), 'game', ['black_player_id'], unique=False)
    op.create_index(op.f('ix_game_status'), 'game', ['status'], unique=False)
    op.create_index(op.f('ix_game_white_player_id'), 'game', ['white_player_id'], unique=False)
    op.create_table('position',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fen_norm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zkey', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fen_norm')
    )
    op.create_index(op.f('ix_position_zkey'), 'position', ['zkey'], unique=False)
    op.create_table('game_node',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Uuid(), nullable=False),
    sa.Column('white_clock', sa.Integer(), nullable=True),
    sa.Column('black_clock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'ply')
    )
    op.create_index(op.f('ix_game_node_position_id'), 'game_node', ['position_id'], unique=False)
    op.create_table('preferred_move',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Boolean(), nullable=False),
    sa.Column('position_id', sa.Uuid(), nullable=False),
    sa.Column('next_position_id', sa.Uuid(), nullable=False),
    sa.Column('uci', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['next_position_id'], ['position.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'scope', 'position_id')
    )
    op.create_index(op.f('ix_preferred_move_next_position_id'), 'preferred_move', ['next_position_id'], unique=False)
    op.create_index(op.f('ix_preferred_move_player_id'), 'preferred_move', ['player_id'], unique=False)
    op.create_index(op.f('ix_preferred_move_scope'), 'preferred_move', ['scope'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preferred_move_scope'), table_name='preferred_move')
    op.drop_index(op.f('ix_preferred_move_player_id'), table_name='preferred_move')
    op.drop_index(op.f('ix_preferred_move_next_position_id'), table_name='preferred_move')
    op.drop_table('preferred_move')
    op.drop_index(op.f('ix_game_node_position_id'), table_name='game_node')
    op.drop_table('game_node')
    op.drop_index(op.f('ix_position_zkey'), table_name='position')
    op.drop_table('position')
    op.drop_index(op.f('ix_game_white_player_id'), table_name='game')
    op.drop_index(op.f('ix_game_status'), table_name='game')
    op.drop_index(op.f('ix_game_black_player_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
