"""add from_san to game nodes

Revision ID: 60ae8bde8057
Revises: e0de40853fc7
Create Date: 2025-08-23 14:23:27.731365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '60ae8bde8057'
down_revision: Union[str, Sequence[str], None] = 'e0de40853fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_node', sa.Column('from_san', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_node', 'from_san')
    # ### end Alembic commands ###
