"""drop scope from preferred_move

Revision ID: e0de40853fc7
Revises: 1aa995770ec9
Create Date: 2025-08-23 14:05:59.144517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e0de40853fc7'
down_revision: Union[str, Sequence[str], None] = '1aa995770ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preferred_move_scope'), table_name='preferred_move')
    op.drop_column('preferred_move', 'scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferred_move', sa.Column('scope', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_preferred_move_scope'), 'preferred_move', ['scope'], unique=False)
    # ### end Alembic commands ###
