"""initial tables

Revision ID: e5fff92d00df
Revises:
Create Date: 2025-08-21 00:45:17.991001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "e5fff92d00df"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("fen_norm", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zkey", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fen_norm"),
    )
    op.create_index(op.f("ix_position_zkey"), "position", ["zkey"], unique=False)
    op.create_table(
        "player_move_pref",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pos_from", sa.Uuid(), nullable=False),
        sa.Column("uci", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pos_to", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pos_from"], ["position.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pos_to"], ["position.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "scope", "pos_from"),
    )
    op.create_index(
        op.f("ix_player_move_pref_scope"),
        "player_move_pref",
        ["scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_player_move_pref_user_id"),
        "player_move_pref",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_move_pref_user_id"), table_name="player_move_pref")
    op.drop_index(op.f("ix_player_move_pref_scope"), table_name="player_move_pref")
    op.drop_table("player_move_pref")
    op.drop_index(op.f("ix_position_zkey"), table_name="position")
    op.drop_table("position")
    # ### end Alembic commands ###
